### PR TITLE
fix: do not report diff on adminstate_config when in registered state

### PR DESCRIPTION
**Pull request by fabian-zededa**
Do not report diff on admin state when edge node is in REGISTERED state.

### CODE REVIEW

**Comment by Eun** [comment]
Could you make sure this is not breaking existing behavior?

**Comment by fabian-zededa** [comment]
> Could you make sure this is not breaking existing behavior?

It actually should. The existing behavior is simply wrong. Unfortunately, there are no tests and writing one for this 'deprecated' version is not worth the effort imo. 

The problem is, that this field admin_state can be set by the client, e.g. to ACTIVE but is set to REGISTERED state only by zedcloud once the edge-node is oboarded. This makes updating the local config manually required which counters the whole nature of automation for big amounts of edge-nodes. So client sets to ACTIVE, zedcloud onboards automatically and state is set to REGISTERED. Then terraform client config is out of sync. So we ignore this case when calculating diff. (edited)

**Review by trinitum — APPROVED** [review]

**Comment by Eun** [comment]
I think we need to be sure this is not breaking some customer workflow. 
i would like to loop in the systest team before releasing this.

**Comment by Eun** [comment]
@ppal-zededa could you have a look?

**Pull request merged**
